services:
  - type: web
    name: yolo-object-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GENERATIVE_AI_API_KEY
      - key: FLASK_ENV
        value: "production"
